# 日志轮转配置
/root/projects/Affirm/logs/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 root root
    sharedscripts
    postrotate
        [ -f /root/.pm2/pm2.pid ] && kill -USR2 `cat /root/.pm2/pm2.pid`
    endscript
}
